### ISSUE TITLE
Crash in Android Lollipop

### ISSUE THREAD

**Issue by jasmine-wwm** [Estimote/Android-SDK#100]
I am using Estimote SDK in my application.Its working fine upto 4.4.4.But crashes in Lollipop.I saw that this issue has been fixed in your update.But its still there.Please help me find the issue here.
Please see the crash log below.
Thanks.

java.lang.IllegalArgumentException: This cannot be run on UI thread, starting BLE scan can be expensive
at com.simelabs.kmb.spotbeak.internal.Preconditions.checkArgument(Preconditions.java:39)
at com.simelabs.kmb.spotbeak.service.BeaconService.checkNotOnUiThread(BeaconService.java:507)
at com.simelabs.kmb.spotbeak.service.BeaconService.access$3(BeaconService.java:505)
at com.simelabs.kmb.spotbeak.service.BeaconService$InternalLeScanCallback.onLeScan(BeaconService.java:485)
at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1720)
at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:330)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by wiktor** [comment]
I’m pretty sure that you have not updated the library. In new one there is no such a message. Can you recheck that?

**Comment by jasmine-wwm** [comment]
Ok.Let me confirm once again.

**Comment by jasmine-wwm** [comment]
I am using the latest updated SDK in my project.Could u tell me what is the fix you've done to support Lollipop?Icouldn't resolve this :(

**Comment by wiktor** [comment]
The bug was inside the SDK which is closed source.




Can you remove old library? (like really remove it) and re add it again?

Can you tell me what is the jar size of the library? (just double checking)

How are you building the app? Maybe library is cached somewhere and you need to clear all caches.

**Comment by jasmine-wwm** [comment]
Is there any sample app which i can use to test the new sdk ?I want to confirm that my sdk is updated one.Please help.

**Comment by wiktor** [comment]
Check out examples in SDK.

**Comment by siranjeevir** [comment]
Hi Wiktor,
                 Now am learning your SDK. I saw previous comments on EstimoteAndroid SDK. I need to know whether it will work or not? on Android platform. If yes, means i need to know Which SDK version is minimum needed. You have any updated SDK ? Please help.

**Comment by wiktor** [comment]
Estimote Android SDK works on Androids 4.3 or above.

**Comment by joakimjonsson** [comment]
I also get the ForceClose error mention above in Android 5 lollipop.
I've removed old sdk from Project and then readded the new sdk but error is still there...

/joakim
