### ISSUE TITLE
Crash after update to 0.8 version.

### ISSUE THREAD

**Issue by rafalniski** [Estimote/Android-SDK#117]
Hi,

after upgrading library to 0.8 version I started getting this error:

    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference 
       at com.estimote.sdk.repackaged.android_21.ScanRecord.getManufacturerSpecificData(ScanRecord.java:99)
       at com.estimote.sdk.Utils.beaconFromLeScan(Utils.java:56)
       at com.estimote.sdk.service.BeaconService$2$1.run(BeaconService.java:479)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

Any ideas what might be the case?

**Comment by wiktor** [comment]
@rafalniski We also did spot this bug. SDK with bugfix will be released by tomorrow.

**Comment by wiktor** [comment]
Fixed with version 0.8.2. Sorry for that.

**Comment by rafalniski** [comment]
@wiktor Cool, thanks!
