### ISSUE TITLE
i get this exception with 0.9.7

### ISSUE THREAD

**Issue by leviyehonatan** [Estimote/Android-SDK#139]
```
01-25 10:58:11.123 8671-8671/com.woorlds.kotlintestapp I/EstimoteSDK: com.estimote.sdk.service.BeaconService.onCreate:233 Creating service
01-25 10:58:11.713 8671-9825/com.woorlds.kotlintestapp A/EstimoteSDK: com.estimote.sdk.service.internal.LollipopBluetoothAdapter.stop:175 BluetoothAdapter throws unexpected exception
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
                                                                          at android.os.Parcel.readException(Parcel.java:1546)
                                                                          at android.os.Parcel.readException(Parcel.java:1493)
                                                                          at android.bluetooth.IBluetoothGatt$Stub$Proxy.unregisterClient(IBluetoothGatt.java:905)
                                                                          at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.stopLeScan(BluetoothLeScanner.java:308)
                                                                          at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:167)
                                                                          at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.stop(LollipopBluetoothAdapter.java:171)
                                                                          at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.updateScanSettings(LollipopBluetoothAdapter.java:110)
                                                                          at com.estimote.sdk.service.BeaconService.updateScanPeriods(BeaconService.java:457)
                                                                          at com.estimote.sdk.service.BeaconService.startScanning(BeaconService.java:419)
                                                                          at com.estimote.sdk.service.BeaconService.startMonitoring(BeaconService.java:362)
                                                                          at com.estimote.sdk.service.BeaconService.access$600(BeaconService.java:77)
                                                                          at com.estimote.sdk.service.BeaconService$IncomingHandler$1.run(BeaconService.java:541)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
01-25 10:58:11.853 8671-9825/com.woorlds.kotlintestapp A/EstimoteSDK: com.estimote.sdk.service.internal.LollipopBluetoothAdapter.stop:175 BluetoothAdapter throws unexpected exception
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Looper android.os.Handler.getLooper()' on a null object reference
                                                                          at android.os.Parcel.readException(Parcel.java:1546)
                                                                          at android.os.Parcel.readException(Parcel.java:1493)
                                                                          at android.bluetooth.IBluetoothGatt$Stub$Proxy.unregisterClient(IBluetoothGatt.java:905)
                                                                          at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.stopLeScan(BluetoothLeScanner.java:308)
                                                                          at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:167)
                                                                          at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.stop(LollipopBluetoothAdapter.java:171)
                                                                          at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.updateScanSettings(LollipopBluetoothAdapter.java:110)
                                                                          at com.estimote.sdk.service.BeaconService.updateScanPeriods(BeaconService.java:457)
                                                                          at com.estimote.sdk.service.BeaconService.startScanning(BeaconService.java:419)
                                                                          at com.estimote.sdk.service.BeaconService.startMonitoring(BeaconService.java:362)
                                                                          at com.estimote.sdk.service.BeaconService.access$600(BeaconService.java:77)
                                                                          at com.estimote.sdk.service.BeaconService$IncomingHandler$1.run(BeaconService.java:541)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:145)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rafalniski** [comment]
+1

**Comment by Poberro** [comment]
I seems to be an old Android bug:
https://code.google.com/p/android/issues/detail?id=160503
Exception is caught in SDK 0.10.0 so it does not crash. Closing the issue.
