### ISSUE TITLE
IllegalStateException when starting bluetooth on SDK 0.9.7

### ISSUE THREAD

**Issue by rafalniski** [Estimote/Android-SDK#140]
After upgrade to 0.9.7 the issue with bluetooth still happens:

    Fatal Exception: java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:106)
       at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:101)
       at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.start(LollipopBluetoothAdapter.java:160)
       at com.estimote.sdk.service.internal.LollipopBluetoothAdapter.updateFilters(LollipopBluetoothAdapter.java:133)
       at com.estimote.sdk.service.BeaconService$1.onRegionsChanged(BeaconService.java:246)
       at com.estimote.sdk.service.internal.RegionObserver.onRegionsChanged(RegionObserver.java:90)
       at com.estimote.sdk.service.internal.RegionObserver.add(RegionObserver.java:51)
       at com.estimote.sdk.service.BeaconService.startMonitoring(BeaconService.java:358)
       at com.estimote.sdk.service.BeaconService.access$600(BeaconService.java:77)
       at com.estimote.sdk.service.BeaconService$IncomingHandler$1.run(BeaconService.java:541)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Poberro** [comment]
This issue is fixed in SDK 0.10.0
