### ISSUE TITLE
crash : com.estimote.sdk.internal.utils.AsyncCache$1.onFailure (AsyncCache.java:106)

### ISSUE THREAD

**Issue by mahmooddagga** [Estimote/Android-SDK#149]
AsyncCache.java line 106
com.estimote.sdk.internal.utils.AsyncCache$1.onFailure
****************
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
       at com.estimote.sdk.internal.utils.AsyncCache$1.onFailure(AsyncCache.java:106)
       at com.estimote.sdk.service.internal.SecureUuidResolver$1$1.failure(SecureUuidResolver.java:36)
       at com.estimote.sdk.cloud.internal.InternalEstimoteCloud$6.failure(InternalEstimoteCloud.java:336)
       at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)

**Comment by mahmooddagga** [comment]
Where are they

**Comment by mahmooddagga** [comment]
@Poberro @martinklimek

**Comment by pawelDylag** [comment]
Hello @mahmooddagga !
Sorry for the delay, we were really busy recently. As for your crash - It should have never happened indeed. I have added this to our scope, and It shall be fixed in the next release. Thanks for reporting!
