### ISSUE TITLE
Google API Key logcat spam

### ISSUE THREAD

**Issue by shmuelr** [Estimote/Android-SDK#152]
Hey, since version 0.10.3 logcat is getting filled with this statement

 com.estimote.sdk.service.BeaconService$6.onLeScan:957 Eddystone EID packet parsing error
                                                                      java.lang.NullPointerException: You need to initialize Google API Key first. EstimoteSDK.setGoogleApiKey(key)
                                                                          at com.estimote.sdk.internal.Preconditions.checkNotNull(Preconditions.java:21)
                                                                          at com.estimote.sdk.cloud.ProximityBeaconCloud.getInstance(ProximityBeaconCloud.java:45)
                                                                          at com.estimote.sdk.service.internal.EidResolver$1.load(EidResolver.java:35)
                                                                          at com.estimote.sdk.service.internal.EidResolver$1.load(EidResolver.java:32)
                                                                          at com.estimote.sdk.internal.utils.AsyncCache.get(AsyncCache.java:155)
                                                                          at com.estimote.sdk.service.internal.EidResolver.tryToResolve(EidResolver.java:63)
                                                                          at com.estimote.sdk.service.BeaconService$6.onLeScan(BeaconService.java:946)
                                                                          at com.estimote.sdk.service.BeaconService$3$1.run(BeaconService.java:394)
                                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pawelDylag** [comment]
Hey @shmuelr !
I just fixed that in version 0.10.4 - please check it out and let me know if that works :)
Have a nice day!
