### ISSUE TITLE
Cannot sync non_strict_mode_enabled from cloud

### ISSUE THREAD

**Issue by dibaryon** [Estimote/Android-SDK#160]
The current Android SDK (0.10.8) does not sync the setting non_strict_mode_enabled from the cloud correctly. Reading device details using EstimoteCloud.fetchDeviceDetails I can see the pending settings:

```
 "pending_settings": {
   "advertisers": {
     "ibeacon": [
       {
         ...
         "non_strict_mode_enabled": true,
         ...
       }
     ]
   }
 },

 "settings": {
   "advertisers": {
     "ibeacon": [
       {
         ...
         "non_strict_mode_enabled": false,
         ...
       }
     ]
   },
   ...
 }
```

However, reading com.estimote.sdk.connection.settings.Beacon.nonStrictMode always returns false.

Note: this problem also seem to exists within the current Estimote Android app (1.7.6). After changing the advertising interval within that app, the following exception occurs everytime the Estimote app syncs with the cloud:

```
 com.estimote.sdk.connection.internal.DeviceCloudSyncEngine$4.failure:193 Notify failed: {"errors":[{"identifier":"...","errors":[{"type":"any.allowOnly","message":"\"interval\" must equal 100 when non_strict_mode_enabled is set to false","source":{"path":"settings.advertisers.ibeacon.0.interval"}}]}]}
 com.estimote.sdk.exception.EstimoteServerException: 400 Bad Request
   at com.estimote.sdk.cloud.internal.InternalEstimoteCloud$7.failure(InternalEstimoteCloud.java:363)
   at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:158)
   at android.app.ActivityThread.main(ActivityThread.java:7229)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
 Caused by: com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RetrofitError: 400 Bad Request
   at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:387)
   at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.access$000(RestAdapter.java:219)
   at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler$1.obtainResponse(RestAdapter.java:277)
   at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
   at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.Platform$Android$2$1.run(Platform.java:134)
   at java.lang.Thread.run(Thread.java:818)
```

**Comment by pawelDylag** [comment]
Fixed in recent versions.
