### ISSUE TITLE
FATAL EXCEPTION: BeaconServiceThread

### ISSUE THREAD

**Issue by Moudi2020** [Estimote/Android-SDK#168]
FATAL EXCEPTION: BeaconServiceThread
                                                                   Process: go.heer.com.debug, PID: 14877
                                                                   java.lang.NullPointerException: cancel() called with a null PendingIntent
                                                                       at android.app.AlarmManager.cancel(AlarmManager.java:890)
                                                                       at com.estimote.sdk.service.BeaconService$ScanAlarmBroadcastReceiver.cancelAlarm(BeaconService.java:110)
                                                                       at com.estimote.sdk.service.internal.NoCycleBluetoothScanScheduler.cancelAlarm(NoCycleBluetoothScanScheduler.java:240)
                                                                       at com.estimote.sdk.service.internal.NoCycleBluetoothScanScheduler.destroy(NoCycleBluetoothScanScheduler.java:138)
                                                                       at com.estimote.sdk.service.BeaconService$2.run(BeaconService.java:367)
                                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by Moudi2020** [comment]
This is running on android N.

**Comment by pawelDylag** [comment]
Hello @Moudi2020 
This is a known issue, already reported. We are working on update for android N. Stay tuned for release (soon).

**Comment by pawelDylag** [comment]
Fixed in 0.12.0.
