### ISSUE TITLE
Android signed apk with estimote sdk

### ISSUE THREAD

**Issue by Sharprender** [Estimote/Android-SDK#169]
As debug version my app runs very well.
But if I create a signed apk, it crashes.

```
java.lang.RuntimeException: Unable to bind to service com.estimote.sdk.service.BeaconService@260b2309 with Intent { cmp=zzzzzzzzzz/com.estimote.sdk.service.BeaconService }: java.lang.IllegalArgumentException: InternalEstimoteApi.getBeacons: Last parameter must be of type Callback<X> or Callback<? super X>.

at android.app.ActivityThread.handleBindService(ActivityThread.java:3035)
at android.app.ActivityThread.access$1900(ActivityThread.java:178)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5637)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by: java.lang.IllegalArgumentException: InternalEstimoteApi.getBeacons: Last parameter must be of type Callback<X> or Callback<? super X>.
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestMethodInfo.methodError(Unknown Source)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestMethodInfo.parseResponseType(Unknown Source)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestMethodInfo.<init>(Unknown Source)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter.getMethodInfo(Unknown Source)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.invoke(Unknown Source)
at java.lang.reflect.Proxy.invoke(Proxy.java:397)
at $Proxy1.getBeacons(Unknown Source)
at com.estimote.sdk.cloud.internal.InternalEstimoteCloud.getBeacons(Unknown Source)
at com.estimote.sdk.cloud.internal.AnalyticsManager.fetchOwnedDevicesIfEnabled(Unknown Source)
at com.estimote.sdk.service.BeaconService.onBind(Unknown Source)
at android.app.ActivityThread.handleBindService(ActivityThread.java:3022)
at android.app.ActivityThread.access$1900(ActivityThread.java:178) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558) 
at android.os.Handler.dispatchMessage(Handler.java:111) 
at android.os.Looper.loop(Looper.java:194) 
at android.app.ActivityThread.main(ActivityThread.java:5637) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
```

My proguard-rules.txt contains:

```
-keep class com.estimote.sdk.** { *; }
-keep interface com.estimote.sdk.** { *; }
-dontwarn com.estimote.sdk.**
```

After some debugging, I found the lines, where it happens:

```
EstimoteSDK.initialize(App.getAppContext(), "XXX", "XXX");
EstimoteCloud estimoteCloud = EstimoteCloud.getInstance();
```

But, remember, that installation in Android Studio via USB runs perfect.

What could be a problem?

P.S. I tested it on Samsung Galaxy S6 edge with Android 6.0.1 and on Ruggear 730 with Android 5.1.0

**Comment by pawelDylag** [comment]
Hello @Sharprender 

We are preparing better support for Proguard - I know, that sometimes it obfuscates some files that are later being not found on runtime. From logs I can see that some classes from Analytics are being a part of this bug - maybe it is due to our old cloud endpoint - I need to check that. I just ask you to turn off Analytics in our EstimoteSDK class:
``` Java
enableMonitoringAnalytics(false);
enableRangingAnalytics(false);
```
Please inform me if that changes anything. We will fix that, don't worry :)

**Comment by Sharprender** [comment]
@pawelDylag 
```
enableMonitoringAnalytics(false);
enableRangingAnalytics(false);
```

It seem to run, if I build a signed APK with this two lines.

thx
