### ISSUE TITLE
Android 7.0 crash 

### ISSUE THREAD

**Issue by bstokrocki** [Estimote/Android-SDK#173]
Hello,
I've experienced few crashes of Estimote SDK (v0.12.0) on Nexus 5X running Android Nougat. Here is the stack trace:

`Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at com.estimote.sdk.cloud.internal.AnalyticsManager.generateEvents(AnalyticsManager.java:137)
       at com.estimote.sdk.service.BeaconService.invokeCallbacks(BeaconService.java:681)
       at com.estimote.sdk.service.BeaconService.access$5000(BeaconService.java:93)
       at com.estimote.sdk.service.BeaconService$7.onScanCycleCompleted(BeaconService.java:1072)
       at com.estimote.sdk.service.BeaconService$6.run(BeaconService.java:928)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

Crashes happened few times while app was running in background.

**Comment by pawelDylag** [comment]
Hello @bstokrocki 

Thanks for reporting that - we cannot reproduce that for now, but we will add more protection for this case. Will get you informed as soon as possible.
