### ISSUE TITLE
Detect my beacon failed AnalyticsManager$2.failure:250

### ISSUE THREAD

**Issue by jitongkai** [Estimote/Android-SDK#180]
I get this when I want to get my own beacon's information.
when I called this, ConfigurableDevicesScanner.scanForDevices()

com.estimote.sdk.cloud.internal.AnalyticsManager$2.failure:250 Unable to obtain owned devices for Analytics
                                                      com.estimote.sdk.exception.EstimoteServerException: 503 Service Unavailable
                                                          at com.estimote.sdk.cloud.internal.InternalEstimoteCloud$7.failure(InternalEstimoteCloud.java:391)
                                                          at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
                                                          at android.os.Handler.handleCallback(Handler.java:739)
                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                          at android.os.Looper.loop(Looper.java:135)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5528)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
                                                       Caused by: com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RetrofitError: 503 Service Unavailable
                                                          at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:387)
                                                          at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.access$000(RestAdapter.java:219)
                                                          at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler$1.obtainResponse(RestAdapter.java:277)
                                                          at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                          at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.Platform$Android$2$1.run(Platform.java:134)
                                                          at java.lang.Thread.run(Thread.java:818)

**Comment by pawelDylag** [comment]
Hello @jitongkai  - please tell me if this works now for you. It seems that our cloud service was down for a moment on that day.

**Comment by morganzysman** [comment]
Still not working for me

**Comment by pawelDylag** [comment]
Hello @morganzysman 

Could you check the freshly released version 1.0.0 ([See also the migration guide](https://github.com/Estimote/Android-SDK/blob/master/Docs/switching_to_1.0.0.md)) ?
From the logs provided I can see, that the reason is http response "503 Service Unavailable" from our cloud. This may be the problem on Cloud side. But I need to know if it still occurs in order to investigate further. 
Have a nice day!
