### ISSUE TITLE
Issues with Analytics on Android

### ISSUE THREAD

**Issue by petezajot** [Estimote/Android-SDK#194]
I have an issue with analytics on android
i put this code in my onCreate method:

`EstimoteSDK.initialize(this, "here my appID", "here my appToken");
EstimoteSDK.enableMonitoringAnalytics(true);`

and i get this on my log:

`E/EstimoteSDK: com.estimote.sdk.cloud.internal.analytics.AnalyticsManager$2.failure:260 Unable to obtain owned devices for Analytics
com.estimote.sdk.exception.EstimoteServerException: 503 Service Unavailable
at com.estimote.sdk.cloud.internal.InternalEstimoteCloud$7.failure(InternalEstimoteCloud.java:467)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RetrofitError: 503 Service Unavailable
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:387)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler.access$000(RestAdapter.java:219)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.RestAdapter$RestHandler$1.obtainResponse(RestAdapter.java:277)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at com.estimote.sdk.repackaged.retrofit_v1_9_0.retrofit.Platform$Android$2$1.run(Platform.java:134)
at java.lang.Thread.run(Thread.java:818)
`
somebody can help me please!!!

**Comment by pawelDylag** [comment]
Hello @petezajot !

It seems that our cloud service was down for a moment. Could you confirm that this is not a problem anymore?
