### ISSUE TITLE
NullPointerException on Android API 19

### ISSUE THREAD

**Issue by WolfAlexander** [Estimote/Android-SDK#214]
Hi! I just started using Estimote SDK and got a problem.

I am getting NullPointerException on Samsung Galaxy Trend 2 Lite  Android 4.4.4 API 19:
`java.lang.NullPointerException
                                                                               at com.estimote.coresdk.scanning.scheduling.KitKatScanScheduler.startOrRestart(KitKatScanScheduler.java:81)
                                                                               at com.estimote.coresdk.scanning.module.ScanningModuleImpl.startScanning(ScanningModuleImpl.java:81)
                                                                               at com.estimote.coresdk.service.EstimoteScanningStack.startScanning(EstimoteScanningStack.java:227)
                                                                               at com.estimote.coresdk.service.EstimoteScanningStack.startMonitoring(EstimoteScanningStack.java:117)
                                                                               at com.estimote.coresdk.service.BeaconService.startMonitoring(BeaconService.java:197)
                                                                               at com.estimote.coresdk.service.BeaconServiceMessengerImpl$1.run(BeaconServiceMessengerImpl.java:83)
                                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)`

To make sure that I did not messed up with my application I tried Notification app from the examples. 
It works with given `com.estimote:sdk:0.10.+@aar`. 
If I change to `'com.estimote:sdk:1.0.2:release@aar`, fix imports, change MonitoringListener to 
BeaconMonitoringListener, chage Region to BeaconRegion - getting the exception when running.

Tried running on LG Spirit with Android 6.0 API 23 - works.

**Comment by pawelDylag** [comment]
Hey @WolfAlexander 

Huge thanks for reporting that - this is already fixed and is scheduled for next release soon :)

Cheers!

**Comment by WolfAlexander** [comment]
Good! Thanks!

**Comment by manishpatelgt** [comment]
@pawelDylag did you guys fixed this issue ? I saw crash in Estimote SDK 1.0.3 too.
