### ISSUE TITLE
Bug in an app using estimote SDK (old version)

### ISSUE THREAD

**Issue by boumero** [Estimote/Android-SDK#223]
Hello every body!
when i start the scan for near beacons, the app stops and shows the following msg, thank you for help

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.finalapp, PID: 5145
                  java.lang.IllegalArgumentException: This cannot be run on UI thread, starting BLE scan can be expensive
                      at com.estimote.sdk.internal.Preconditions.checkArgument(Preconditions.java:65)
                      at com.estimote.sdk.service.BeaconService.checkNotOnUiThread(BeaconService.java:502)
                      at com.estimote.sdk.service.BeaconService.access$600(BeaconService.java:61)
                      at com.estimote.sdk.service.BeaconService$InternalLeScanCallback.onLeScan(BeaconService.java:490)
                      at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1824)
                      at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run(BluetoothLeScanner.java:331)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:159)
                      at android.app.ActivityThread.main(ActivityThread.java:5461)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
I/Process: Sending signal. PID: 5145 SIG: 9
V/Process: killProcess [5145] Callers=com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:99 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 <bottom of call stack> 
Disconnected from the target VM, address: 'localhost:8600', transport: 'socket'

**Comment by pawelDylag** [comment]
Hello @boumero 

Which version of SDK are you using?

**Comment by boumero** [comment]
Thank you Mr. @pawelDylag its was resolved by updating Estimote SDK to a newer version

**Comment by pawelDylag** [comment]
Glad to hear that! Let me know if you encounter any more problems :)

**Comment by boumero** [comment]
hello Mr. Pawel Dylag
I am sorry, I will disturb you ;
I am a beginner in the field, because of my thesis in topography..
so, the problem which i encountered after updating the SDK to 0.8.6 version
is that a lot of methods are not recognized now, so I realize that i should
make some modifications in my code but I didn't find  changes which I
should make anywhere.
can you please give me where are them
Thank you previousely

2017-05-31 13:47 GMT+00:00 Pawel Dylag <notifications@github.com>:
