### ISSUE TITLE
ScanningModule doesn't have lastScanParams initialized

### ISSUE THREAD

**Issue by LuckyLuke75** [Estimote/Android-SDK#263]
Hi,

I just switched from SDK version 0.16.0 to 1.4.0 and I'm getting some crashs reported in production and I have absolutely no idea where this is coming from as I didn't make any major changes to my BeaconService logic and in my Motorola G 3rd gen it's working perfectly.

I don't have much info but I think (as it is a newly release app) that people were not in any region or detecting any beacons. I've had 28 crashes for 9 users so far over a period of two days.

I changed my application to be MultiDex too altough I'm not sure that's where the problem is coming from, any ideas ?

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'com.estimote.coresdk.scanning.internal.ScanType com.estimote.coresdk.scanning.bluetooth.settings.EstimoteScanParams.getScanType()' on a null object reference
       at com.estimote.coresdk.scanning.module.ScanningModuleImpl.changeCurrentScanPeriods(ScanningModuleImpl.java:99)
       at com.estimote.coresdk.service.EstimoteScanningStack.setForegroundScanPeriod(EstimoteScanningStack.java:94)
       at com.estimote.coresdk.service.BeaconService.setForegroundScanPeriod(BeaconService.java:150)
       at com.estimote.coresdk.service.BeaconServiceMessengerImpl$1.run(BeaconServiceMessengerImpl.java:194)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.os.HandlerThread.run(HandlerThread.java:61)

### Manufacturer 
Samsung      30%
HUAWEI       19%
Motorola      19%
LGE              13%
LENOVO      19%

### Android version
5      63%
6      31%
7      6%

Thanks,
Romain

**Comment by ociepa** [comment]
Hi @LuckyLuke75 
We recommend checking out [this guide](https://github.com/Estimote/Android-SDK/blob/master/Docs/switching_to_1.0.0.md) when upgrading from a version lower than 1.0.0. 
Additionally, you may also want to take a look at our [new Proximity SDK](https://github.com/Estimote/Android-Proximity-SDK) — it's better suited for devices running Android M and up.

**Comment by Poberro** [comment]
This should be fixed in maintenance release 1.4.1
