### ISSUE TITLE
Service crashes when stopping a scan

### ISSUE THREAD

**Issue by cmelchior** [Estimote/Android-SDK#44]
If you run the demo app with v0.4.1 of the SDK it crashes the bluetooth service when trying to do a distance scan on a Nexus 4 with Android 4.4.2.

```
04-25 07:39:59.642  32474-32489/com.trifork.estimote D/BluetoothAdapter﹕ stopLeScan()
04-25 07:39:59.662  32474-32489/com.trifork.estimote A/EstimoteSDK﹕ com.estimote.sdk.service.BeaconService.stopScanning:286 BluetoothAdapter throws unexpected exception
    java.lang.NullPointerException
            at android.bluetooth.BluetoothAdapter$GattCallbackWrapper.stopLeScan(BluetoothAdapter.java:1596)
            at android.bluetooth.BluetoothAdapter.stopLeScan(BluetoothAdapter.java:1540)
            at com.estimote.sdk.service.BeaconService.stopScanning(BeaconService.java:284)
            at com.estimote.sdk.service.BeaconService.access$700(BeaconService.java:61)
            at com.estimote.sdk.service.BeaconService$1$1.run(BeaconService.java:524)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by NoceloEder** [comment]
I have the same problem ... anyone solve this ?
