### ISSUE TITLE
Problem with Android 5 (Nexus 6)

### ISSUE THREAD

**Issue by MikeGWem** [Estimote/Android-SDK#92]
I have an app using Estimote beacons that runs happily on Android 4 devices (Nexus 7 and a rooted Nexus 10) using the Dalvik runtime. Testng on a Nexus 6 (Android 5 and Art runtime) the app crashes on executing the following line

beaconManager.startRanging(ALL_ESTIMOTE_BEACONS_REGION);

The log shows:

```
java.lang.IllegalArgumentException: This cannot be run on UI thread, starting BLE scan can be expensive
12-09 14:05:46.768: E/AndroidRuntime(1363):     at   com.estimote.sdk.internal.Preconditions.checkArgument(Preconditions.java:65)
12-09 14:05:46.768: E/AndroidRuntime(1363):     at com.estimote.sdk.service.BeaconService.checkNotOnUiThread(BeaconService.java:502)
12-09 14:05:46.768: E/AndroidRuntime(1363):     at com.estimote.sdk.service.BeaconService.access$600(BeaconService.java:61)
12-09 14:05:46.768: E/AndroidRuntime(1363):     at com.estimote.sdk.service.BeaconService$InternalLeScanCallback.onLeScan(BeaconService.java:490)
12-09 14:05:46.768: E/AndroidRuntime(1363):     at android.bluetooth.BluetoothAdapter$2.onScanResult(BluetoothAdapter.java:1704)
12-09 14:05:46.768: E/AndroidRuntime(1363):     at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper$1.run
```

**Comment by mohdhise** [comment]
where to get latest estimote-sdk-preview.jar for eclipse?

**Comment by wiktor** [comment]
We switched to aar (android archive) distribution. Please do follow new install instructions and update your gradle file.
